name: Process Registration
on:
  issues:
    types: [opened]

jobs:
  process-registration:
    if: contains(github.event.issue.title, 'Registration Request')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract Registration Info
        id: registration
        run: |
          BODY="${{ github.event.issue.body }}"
          EMAIL=$(echo "$BODY" | grep "Email:" | cut -d':' -f2 | tr -d ' ')
          DISPLAY_NAME=$(echo "$BODY" | grep "Display Name:" | cut -d':' -f2 | tr -d ' ')
          echo "email=$EMAIL" >> $GITHUB_OUTPUT
          echo "display_name=$DISPLAY_NAME" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Get Access Token
        run: |
          token=$(curl -X POST "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -d "scope=https://graph.microsoft.com/.default" \
          -d "grant_type=client_credentials" | jq -r '.access_token')
          echo "ACCESS_TOKEN=$token" >> $GITHUB_ENV

      - name: Invite Guest User
        run: |
          curl -X POST "https://graph.microsoft.com/v1.0/invitations" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data-raw '{
            "invitedUserEmailAddress": "${{ steps.registration.outputs.email }}",
            "inviteRedirectUrl": "https://portal.azure.com",
            "sendInvitationMessage": true,
            "invitedUserDisplayName": "${{ steps.registration.outputs.display_name }}"
          }'

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Registration processed successfully. An invitation has been sent to the email address."

      - name: Logout from Azure
        run: az logout
        if: always()
